import { Surah, SurahDetail } from '@/types/quran';

export const STATIC_SURAHS: Surah[] = [
  { number: 1, name: "سُورَةُ الْفَاتِحَةِ", englishName: "Al-Faatiha", englishNameTranslation: "The Opening", numberOfAyahs: 7, revelationType: "Meccan", turkishName: "Fatiha" },
  { number: 2, name: "سُورَةُ الْبَقَرَةِ", englishName: "Al-Baqara", englishNameTranslation: "The Cow", numberOfAyahs: 286, revelationType: "Medinan", turkishName: "Bakara" },
  { number: 3, name: "سُورَةُ آلِ عِمْرَانَ", englishName: "Aal-i-Imraan", englishNameTranslation: "The Family of Imraan", numberOfAyahs: 200, revelationType: "Medinan", turkishName: "Âl-i İmrân" },
  { number: 4, name: "سُورَةُ النِّسَاءِ", englishName: "An-Nisaa", englishNameTranslation: "The Women", numberOfAyahs: 176, revelationType: "Medinan", turkishName: "Nisâ" },
  { number: 5, name: "سُورَةُ الْمَائِدَةِ", englishName: "Al-Maaida", englishNameTranslation: "The Table", numberOfAyahs: 120, revelationType: "Medinan", turkishName: "Mâide" },
  { number: 6, name: "سُورَةُ الْأَنْعَامِ", englishName: "Al-An'aam", englishNameTranslation: "The Cattle", numberOfAyahs: 165, revelationType: "Meccan", turkishName: "En'âm" },
  { number: 7, name: "سُورَةُ الْأَعْرَافِ", englishName: "Al-A'raaf", englishNameTranslation: "The Heights", numberOfAyahs: 206, revelationType: "Meccan", turkishName: "A'râf" },
  { number: 8, name: "سُورَةُ الْأَنْفَالِ", englishName: "Al-Anfaal", englishNameTranslation: "The Spoils of War", numberOfAyahs: 75, revelationType: "Medinan", turkishName: "Enfâl" },
  { number: 9, name: "سُورَةُ التَّوْبَةِ", englishName: "At-Tawba", englishNameTranslation: "The Repentance", numberOfAyahs: 129, revelationType: "Medinan", turkishName: "Tevbe" },
  { number: 10, name: "سُورَةُ يُونُسَ", englishName: "Yunus", englishNameTranslation: "Jonah", numberOfAyahs: 109, revelationType: "Meccan", turkishName: "Yûnus" },
  { number: 11, name: "سُورَةُ هُودٍ", englishName: "Hud", englishNameTranslation: "Hud", numberOfAyahs: 123, revelationType: "Meccan", turkishName: "Hûd" },
  { number: 12, name: "سُورَةُ يُوسُفَ", englishName: "Yusuf", englishNameTranslation: "Joseph", numberOfAyahs: 111, revelationType: "Meccan", turkishName: "Yûsuf" },
  { number: 13, name: "سُورَةُ الرَّعْدِ", englishName: "Ar-Ra'd", englishNameTranslation: "The Thunder", numberOfAyahs: 43, revelationType: "Medinan", turkishName: "Ra'd" },
  { number: 14, name: "سُورَةُ إِبْرَاهِيمَ", englishName: "Ibrahim", englishNameTranslation: "Abraham", numberOfAyahs: 52, revelationType: "Meccan", turkishName: "İbrâhîm" },
  { number: 15, name: "سُورَةُ الْحِجْرِ", englishName: "Al-Hijr", englishNameTranslation: "The Rocky Tract", numberOfAyahs: 99, revelationType: "Meccan", turkishName: "Hicr" },
  { number: 16, name: "سُورَةُ النَّحْلِ", englishName: "An-Nahl", englishNameTranslation: "The Bee", numberOfAyahs: 128, revelationType: "Meccan", turkishName: "Nahl" },
  { number: 17, name: "سُورَةُ الْإِسْرَاءِ", englishName: "Al-Israa", englishNameTranslation: "The Night Journey", numberOfAyahs: 111, revelationType: "Meccan", turkishName: "İsrâ" },
  { number: 18, name: "سُورَةُ الْكَهْفِ", englishName: "Al-Kahf", englishNameTranslation: "The Cave", numberOfAyahs: 110, revelationType: "Meccan", turkishName: "Kehf" },
  { number: 19, name: "سُورَةُ مَرْيَمَ", englishName: "Maryam", englishNameTranslation: "Mary", numberOfAyahs: 98, revelationType: "Meccan", turkishName: "Meryem" },
  { number: 20, name: "سُورَةُ طه", englishName: "Taa-Haa", englishNameTranslation: "Ta-Ha", numberOfAyahs: 135, revelationType: "Meccan", turkishName: "Tâhâ" },
  { number: 21, name: "سُورَةُ الْأَنْبِيَاءِ", englishName: "Al-Anbiyaa", englishNameTranslation: "The Prophets", numberOfAyahs: 112, revelationType: "Meccan", turkishName: "Enbiyâ" },
  { number: 22, name: "سُورَةُ الْحَجِّ", englishName: "Al-Hajj", englishNameTranslation: "The Pilgrimage", numberOfAyahs: 78, revelationType: "Medinan", turkishName: "Hac" },
  { number: 23, name: "سُورَةُ الْمُؤْمِنُونَ", englishName: "Al-Mu'minoon", englishNameTranslation: "The Believers", numberOfAyahs: 118, revelationType: "Meccan", turkishName: "Mü'minûn" },
  { number: 24, name: "سُورَةُ النُّورِ", englishName: "An-Noor", englishNameTranslation: "The Light", numberOfAyahs: 64, revelationType: "Medinan", turkishName: "Nûr" },
  { number: 25, name: "سُورَةُ الْفُرْقَانِ", englishName: "Al-Furqaan", englishNameTranslation: "The Criterion", numberOfAyahs: 77, revelationType: "Meccan", turkishName: "Furkân" },
  { number: 26, name: "سُورَةُ الشُّعَرَاءِ", englishName: "Ash-Shu'araa", englishNameTranslation: "The Poets", numberOfAyahs: 227, revelationType: "Meccan", turkishName: "Şuarâ" },
  { number: 27, name: "سُورَةُ النَّمْلِ", englishName: "An-Naml", englishNameTranslation: "The Ant", numberOfAyahs: 93, revelationType: "Meccan", turkishName: "Neml" },
  { number: 28, name: "سُورَةُ الْقَصَصِ", englishName: "Al-Qasas", englishNameTranslation: "The Stories", numberOfAyahs: 88, revelationType: "Meccan", turkishName: "Kasas" },
  { number: 29, name: "سُورَةُ الْعَنْكَبُوتِ", englishName: "Al-Ankaboot", englishNameTranslation: "The Spider", numberOfAyahs: 69, revelationType: "Meccan", turkishName: "Ankebût" },
  { number: 30, name: "سُورَةُ الرُّومِ", englishName: "Ar-Room", englishNameTranslation: "The Romans", numberOfAyahs: 60, revelationType: "Meccan", turkishName: "Rûm" },
  { number: 31, name: "سُورَةُ لُقْمَانَ", englishName: "Luqman", englishNameTranslation: "Luqman", numberOfAyahs: 34, revelationType: "Meccan", turkishName: "Lokmân" },
  { number: 32, name: "سُورَةُ السَّجْدَةِ", englishName: "As-Sajda", englishNameTranslation: "The Prostration", numberOfAyahs: 30, revelationType: "Meccan", turkishName: "Secde" },
  { number: 33, name: "سُورَةُ الْأَحْزَابِ", englishName: "Al-Ahzaab", englishNameTranslation: "The Combined Forces", numberOfAyahs: 73, revelationType: "Medinan", turkishName: "Ahzâb" },
  { number: 34, name: "سُورَةُ سَبَإٍ", englishName: "Saba", englishNameTranslation: "Sheba", numberOfAyahs: 54, revelationType: "Meccan", turkishName: "Sebe'" },
  { number: 35, name: "سُورَةُ فَاطِرٍ", englishName: "Faatir", englishNameTranslation: "The Originator", numberOfAyahs: 45, revelationType: "Meccan", turkishName: "Fâtır" },
  { number: 36, name: "سُورَةُ يس", englishName: "Yaseen", englishNameTranslation: "Ya-Seen", numberOfAyahs: 83, revelationType: "Meccan", turkishName: "Yâsîn" },
  { number: 37, name: "سُورَةُ الصَّافَّاتِ", englishName: "As-Saaffaat", englishNameTranslation: "Those Ranges in Ranks", numberOfAyahs: 182, revelationType: "Meccan", turkishName: "Sâffât" },
  { number: 38, name: "سُورَةُ ص", englishName: "Saad", englishNameTranslation: "Sad", numberOfAyahs: 88, revelationType: "Meccan", turkishName: "Sâd" },
  { number: 39, name: "سُورَةُ الزُّمَرِ", englishName: "Az-Zumar", englishNameTranslation: "The Groups", numberOfAyahs: 75, revelationType: "Meccan", turkishName: "Zümer" },
  { number: 40, name: "سُورَةُ غَافِرٍ", englishName: "Ghafir", englishNameTranslation: "The Forgiver", numberOfAyahs: 85, revelationType: "Meccan", turkishName: "Mü'min (Gāfir)" },
  { number: 41, name: "سُورَةُ فُصِّلَتْ", englishName: "Fussilat", englishNameTranslation: "Distinguished", numberOfAyahs: 54, revelationType: "Meccan", turkishName: "Fussilet" },
  { number: 42, name: "سُورَةُ الشُّورَى", englishName: "Ash-Shoora", englishNameTranslation: "The Consultation", numberOfAyahs: 53, revelationType: "Meccan", turkishName: "Şûrâ" },
  { number: 43, name: "سُورَةُ الزُّخْرُفِ", englishName: "Az-Zukhruf", englishNameTranslation: "The Gold Adornments", numberOfAyahs: 89, revelationType: "Meccan", turkishName: "Zuhruf" },
  { number: 44, name: "سُورَةُ الدُّخَانِ", englishName: "Ad-Dukhaan", englishNameTranslation: "The Smoke", numberOfAyahs: 59, revelationType: "Meccan", turkishName: "Duhân" },
  { number: 45, name: "سُورَةُ الْجَاثِيَةِ", englishName: "Al-Jaathiya", englishNameTranslation: "The Kneeling", numberOfAyahs: 37, revelationType: "Meccan", turkishName: "Câsiye" },
  { number: 46, name: "سُورَةُ الْأَحْقَافِ", englishName: "Al-Ahqaaf", englishNameTranslation: "The Curved Sand-hills", numberOfAyahs: 35, revelationType: "Meccan", turkishName: "Ahkâf" },
  { number: 47, name: "سُورَةُ مُحَمَّدٍ", englishName: "Muhammad", englishNameTranslation: "Muhammad", numberOfAyahs: 38, revelationType: "Medinan", turkishName: "Muhammed" },
  { number: 48, name: "سُورَةُ الْفَتْحِ", englishName: "Al-Fath", englishNameTranslation: "The Victory", numberOfAyahs: 29, revelationType: "Medinan", turkishName: "Fetih" },
  { number: 49, name: "سُورَةُ الْحُجُرَاتِ", englishName: "Al-Hujuraat", englishNameTranslation: "The Dwellings", numberOfAyahs: 18, revelationType: "Medinan", turkishName: "Hucurât" },
  { number: 50, name: "سُورَةُ ق", englishName: "Qaaf", englishNameTranslation: "Qaf", numberOfAyahs: 45, revelationType: "Meccan", turkishName: "Kâf" },
  { number: 51, name: "سُورَةُ الذَّارِيَاتِ", englishName: "Adh-Dhaariyat", englishNameTranslation: "The Wind that Scatter", numberOfAyahs: 60, revelationType: "Meccan", turkishName: "Zâriyât" },
  { number: 52, name: "سُورَةُ التُّورِ", englishName: "At-Toor", englishNameTranslation: "The Mount", numberOfAyahs: 49, revelationType: "Meccan", turkishName: "Tûr" },
  { number: 53, name: "سُورَةُ النَّجْمِ", englishName: "An-Najm", englishNameTranslation: "The Star", numberOfAyahs: 62, revelationType: "Meccan", turkishName: "Necm" },
  { number: 54, name: "سُورَةُ الْقَمَرِ", englishName: "Al-Qamar", englishNameTranslation: "The Moon", numberOfAyahs: 55, revelationType: "Meccan", turkishName: "Kamer" },
  { number: 55, name: "سُورَةُ الرَّحْمَنِ", englishName: "Ar-Rahmaan", englishNameTranslation: "The Beneficent", numberOfAyahs: 78, revelationType: "Medinan", turkishName: "Rahmân" },
  { number: 56, name: "سُورَةُ الْوَاقِعَةِ", englishName: "Al-Waaqia", englishNameTranslation: "The Event", numberOfAyahs: 96, revelationType: "Meccan", turkishName: "Vâkıa" },
  { number: 57, name: "سُورَةُ الْحَدِيدِ", englishName: "Al-Hadeed", englishNameTranslation: "The Iron", numberOfAyahs: 29, revelationType: "Medinan", turkishName: "Hadîd" },
  { number: 58, name: "سُورَةُ الْمُجَادِلَةِ", englishName: "Al-Mujaadila", englishNameTranslation: "She That Disputeth", numberOfAyahs: 22, revelationType: "Medinan", turkishName: "Mücâdele" },
  { number: 59, name: "سُورَةُ الْحَشْرِ", englishName: "Al-Hashr", englishNameTranslation: "The Exile", numberOfAyahs: 24, revelationType: "Medinan", turkishName: "Haşr" },
  { number: 60, name: "سُورَةُ الْمُقْتَحِنَةِ", englishName: "Al-Mumtahina", englishNameTranslation: "She That Is to Be Examined", numberOfAyahs: 13, revelationType: "Medinan", turkishName: "Mümtehine" },
  { number: 61, name: "سُورَةُ الصَّفِّ", englishName: "As-Saff", englishNameTranslation: "The Ranks", numberOfAyahs: 14, revelationType: "Medinan", turkishName: "Saf" },
  { number: 62, name: "سُورَةُ الْجُمُعَةِ", englishName: "Al-Jumu'a", englishNameTranslation: "Friday", numberOfAyahs: 11, revelationType: "Medinan", turkishName: "Cuma" },
  { number: 63, name: "سُورَةُ الْمُنَافِقُونَ", englishName: "Al-Munaafiqoon", englishNameTranslation: "The Hypocrites", numberOfAyahs: 11, revelationType: "Medinan", turkishName: "Münâfikûn" },
  { number: 64, name: "سُورَةُ التَّغَابُنِ", englishName: "At-Taghaabun", englishNameTranslation: "Mutual Disillusion", numberOfAyahs: 18, revelationType: "Medinan", turkishName: "Teğâbün" },
  { number: 65, name: "سُورَةُ الطَّلَاقِ", englishName: "At-Talaaq", englishNameTranslation: "Divorce", numberOfAyahs: 12, revelationType: "Medinan", turkishName: "Talâk" },
  { number: 66, name: "سُورَةُ التَّحْرِيمِ", englishName: "At-Tahreem", englishNameTranslation: "Banning", numberOfAyahs: 12, revelationType: "Medinan", turkishName: "Tahrîm" },
  { number: 67, name: "سُورَةُ الْمُلْكِ", englishName: "Al-Mulk", englishNameTranslation: "The Sovereignty", numberOfAyahs: 30, revelationType: "Meccan", turkishName: "Mülk" },
  { number: 68, name: "سُورَةُ الْقَلَمِ", englishName: "Al-Qalam", englishNameTranslation: "The Pen", numberOfAyahs: 52, revelationType: "Meccan", turkishName: "Kalem" },
  { number: 69, name: "سُورَةُ الْحَاقَّةِ", englishName: "Al-Haaqqa", englishNameTranslation: "The Reality", numberOfAyahs: 52, revelationType: "Meccan", turkishName: "Hâkka" },
  { number: 70, name: "سُورَةُ الْمَعَارِجِ", englishName: "Al-Ma'aarij", englishNameTranslation: "The Ascending Stairways", numberOfAyahs: 44, revelationType: "Meccan", turkishName: "Meâric" },
  { number: 71, name: "سُورَةُ نُوحٍ", englishName: "Nooh", englishNameTranslation: "Noah", numberOfAyahs: 28, revelationType: "Meccan", turkishName: "Nûh" },
  { number: 72, name: "سُورَةُ الْجِنِّ", englishName: "Al-Jinn", englishNameTranslation: "The Jinn", numberOfAyahs: 28, revelationType: "Meccan", turkishName: "Cin" },
  { number: 73, name: "سُورَةُ الْمُزَّمِّلِ", englishName: "Al-Muzzammil", englishNameTranslation: "The Enshrouded One", numberOfAyahs: 20, revelationType: "Meccan", turkishName: "Müzemmil" },
  { number: 74, name: "سُورَةُ الْمُدَّثِّرِ", englishName: "Al-Muddaththir", englishNameTranslation: "The Cloaked One", numberOfAyahs: 56, revelationType: "Meccan", turkishName: "Müddessir" },
  { number: 75, name: "سُورَةُ الْقِيَامَةِ", englishName: "Al-Qiyaama", englishNameTranslation: "The Rising of the Dead", numberOfAyahs: 40, revelationType: "Meccan", turkishName: "Kıyâme" },
  { number: 76, name: "سُورَةُ الْإِنْسَانِ", englishName: "Al-Insaan", englishNameTranslation: "Man", numberOfAyahs: 31, revelationType: "Medinan", turkishName: "İnsân" },
  { number: 77, name: "سُورَةُ الْمُرْسَلَاتِ", englishName: "Al-Mursalaat", englishNameTranslation: "The Emissaries", numberOfAyahs: 50, revelationType: "Meccan", turkishName: "Mürselât" },
  { number: 78, name: "سُورَةُ النَّبَإِ", englishName: "An-Naba", englishNameTranslation: "The Tidings", numberOfAyahs: 40, revelationType: "Meccan", turkishName: "Nebe'" },
  { number: 79, name: "سُورَةُ النَّازِعَاتِ", englishName: "An-Naazi'aat", englishNameTranslation: "Those Who Drag Forth", numberOfAyahs: 46, revelationType: "Meccan", turkishName: "Nâziât" },
  { number: 80, name: "سُورَةُ عَبَسَ", englishName: "Abasa", englishNameTranslation: "He Frowned", numberOfAyahs: 42, revelationType: "Meccan", turkishName: "Abese" },
  { number: 81, name: "سُورَةُ التَّكْوِيرِ", englishName: "At-Takweer", englishNameTranslation: "The Overthrowing", numberOfAyahs: 29, revelationType: "Meccan", turkishName: "Tekvîr" },
  { number: 82, name: "سُورَةُ الْإِنْفِطَارِ", englishName: "Al-Infitaar", englishNameTranslation: "The Cleaving", numberOfAyahs: 19, revelationType: "Meccan", turkishName: "İnfitâr" },
  { number: 83, name: "سُورَةُ الْمُطَفِّفِينَ", englishName: "Al-Mutaffifeen", englishNameTranslation: "Defrauding", numberOfAyahs: 36, revelationType: "Meccan", turkishName: "Mutaffifîn" },
  { number: 84, name: "سُورَةُ الِانْشِقَاقِ", englishName: "Al-Inshiqaaq", englishNameTranslation: "The Splitting Asunder", numberOfAyahs: 25, revelationType: "Meccan", turkishName: "İnşikâk" },
  { number: 85, name: "سُورَةُ الْبُرُوجِ", englishName: "Al-Burooj", englishNameTranslation: "The Mansions of the Stars", numberOfAyahs: 22, revelationType: "Meccan", turkishName: "Burûc" },
  { number: 86, name: "سُورَةُ الطَّارِقِ", englishName: "At-Taariq", englishNameTranslation: "The Morning Star", numberOfAyahs: 17, revelationType: "Meccan", turkishName: "Târık" },
  { number: 87, name: "سُورَةُ الْأَعْلَى", englishName: "Al-A'la", englishNameTranslation: "The Most High", numberOfAyahs: 19, revelationType: "Meccan", turkishName: "A'lâ" },
  { number: 88, name: "سُورَةُ الْغَاشِيَةِ", englishName: "Al-Ghaashiya", englishNameTranslation: "The Overwhelming", numberOfAyahs: 26, revelationType: "Meccan", turkishName: "Gāşiye" },
  { number: 89, name: "سُورَةُ الْفَجْرِ", englishName: "Al-Fajr", englishNameTranslation: "The Dawn", numberOfAyahs: 30, revelationType: "Meccan", turkishName: "Fecr" },
  { number: 90, name: "سُورَةُ الْبَلَدِ", englishName: "Al-Balad", englishNameTranslation: "The City", numberOfAyahs: 20, revelationType: "Meccan", turkishName: "Beled" },
  { number: 91, name: "سُورَةُ الشَّمْسِ", englishName: "Ash-Shams", englishNameTranslation: "The Sun", numberOfAyahs: 15, revelationType: "Meccan", turkishName: "Şems" },
  { number: 92, name: "سُورَةُ اللَّيْلِ", englishName: "Al-Lail", englishNameTranslation: "The Night", numberOfAyahs: 21, revelationType: "Meccan", turkishName: "Leyl" },
  { number: 93, name: "سُورَةُ الضُّحَى", englishName: "Ad-Duha", englishNameTranslation: "The Morning Hours", numberOfAyahs: 11, revelationType: "Meccan", turkishName: "Duhâ" },
  { number: 94, name: "سُورَةُ الشَّرْحِ", englishName: "Ash-Sharh", englishNameTranslation: "The Consolation", numberOfAyahs: 8, revelationType: "Meccan", turkishName: "İnşirâh (Şerh)" },
  { number: 95, name: "سُورَةُ التِّينِ", englishName: "At-Teen", englishNameTranslation: "The Fig", numberOfAyahs: 8, revelationType: "Meccan", turkishName: "Tîn" },
  { number: 96, name: "سُورَةُ الْعَلَقِ", englishName: "Al-Alaq", englishNameTranslation: "The Clot", numberOfAyahs: 19, revelationType: "Meccan", turkishName: "Alak" },
  { number: 97, name: "سُورَةُ الْقَدْرِ", englishName: "Al-Qadr", englishNameTranslation: "The Power", numberOfAyahs: 5, revelationType: "Meccan", turkishName: "Kadir" },
  { number: 98, name: "سُورَةُ الْبَيِّنَةِ", englishName: "Al-Bayyina", englishNameTranslation: "The Clear Proof", numberOfAyahs: 8, revelationType: "Medinan", turkishName: "Beyyine" },
  { number: 99, name: "سُورَةُ الزِّلْزَالِ", englishName: "Az-Zalzala", englishNameTranslation: "The Earthquake", numberOfAyahs: 8, revelationType: "Medinan", turkishName: "Zilzâl" },
  { number: 100, name: "سُورَةُ الْعَادِيَاتِ", englishName: "Al-Aadiyaat", englishNameTranslation: "The Courser", numberOfAyahs: 11, revelationType: "Meccan", turkishName: "Âdiyât" },
  { number: 101, name: "سُورَةُ الْقَارِعَةِ", englishName: "Al-Qaari'a", englishNameTranslation: "The Calamity", numberOfAyahs: 11, revelationType: "Meccan", turkishName: "Kāria" },
  { number: 102, name: "سُورَةُ التَّكَاثُرِ", englishName: "At-Takaathur", englishNameTranslation: "Rivalry in World Increase", numberOfAyahs: 8, revelationType: "Meccan", turkishName: "Tekâsür" },
  { number: 103, name: "سُورَةُ الْعَصْرِ", englishName: "Al-Asr", englishNameTranslation: "The Declining Day", numberOfAyahs: 3, revelationType: "Meccan", turkishName: "Asr" },
  { number: 104, name: "سُورَةُ الْهُمَزَةِ", englishName: "Al-Humaza", englishNameTranslation: "The Traducer", numberOfAyahs: 9, revelationType: "Meccan", turkishName: "Hümeze" },
  { number: 105, name: "سُورَةُ الْفِيلِ", englishName: "Al-Fil", englishNameTranslation: "The Elephant", numberOfAyahs: 5, revelationType: "Meccan", turkishName: "Fîl" },
  { number: 106, name: "سُورَةُ قُرَيْشٍ", englishName: "Quraish", englishNameTranslation: "Quraysh", numberOfAyahs: 4, revelationType: "Meccan", turkishName: "Kureyş" },
  { number: 107, name: "سُورَةُ الْمَاعُونِ", englishName: "Al-Maa'oon", englishNameTranslation: "Small Kindnesses", numberOfAyahs: 7, revelationType: "Meccan", turkishName: "Mâûn" },
  { number: 108, name: "سُورَةُ الْكَوْثَرِ", englishName: "Al-Kawthar", englishNameTranslation: "Abundance", numberOfAyahs: 3, revelationType: "Meccan", turkishName: "Kevser" },
  { number: 109, name: "سُورَةُ الْكَافِرُونَ", englishName: "Al-Kaafiroon", englishNameTranslation: "The Disbelievers", numberOfAyahs: 6, revelationType: "Meccan", turkishName: "Kâfirûn" },
  { number: 110, name: "سُورَةُ النَّصْرِ", englishName: "An-Nasr", englishNameTranslation: "Divine Support", numberOfAyahs: 3, revelationType: "Medinan", turkishName: "Nasr" },
  { number: 111, name: "سُورَةُ الْمَسَدِ", englishName: "Al-Masad", englishNameTranslation: "The Palm Fibre", numberOfAyahs: 5, revelationType: "Meccan", turkishName: "Mesed (Tebbet)" },
  { number: 112, name: "سُورَةُ الْإِخْلَاصِ", englishName: "Al-Ikhlaas", englishNameTranslation: "Sincerity", numberOfAyahs: 4, revelationType: "Meccan", turkishName: "İhlâs" },
  { number: 113, name: "سُورَةُ الْفَلَقِ", englishName: "Al-Falaq", englishNameTranslation: "The Daybreak", numberOfAyahs: 5, revelationType: "Meccan", turkishName: "Felak" },
  { number: 114, name: "سُورَةُ النَّاسِ", englishName: "An-Naas", englishNameTranslation: "Mankind", numberOfAyahs: 6, revelationType: "Meccan", turkishName: "Nâs" }
];

export const OFFLINE_SURAH_DETAILS: Record<number, SurahDetail> = {
  1: {
    ...STATIC_SURAHS[0],
    ayahs: [
      { number: 1, numberInSurah: 1, text: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", translation: "Rahmân ve Rahîm olan Allah'ın ismiyle.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1.mp3", juz: 1, page: 1 },
      { number: 2, numberInSurah: 2, text: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", translation: "Hamd, âlemlerin Rabbi olan Allah'a mahsustur.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/2.mp3", juz: 1, page: 1 },
      { number: 3, numberInSurah: 3, text: "الرَّحْمَٰنِ الرَّحِيمِ", translation: "O, Rahmân'dır, Rahîm'dir.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/3.mp3", juz: 1, page: 1 },
      { number: 4, numberInSurah: 4, text: "مَالِكِ يَوْمِ الدِّينِ", translation: "Ceza (hüküm) gününün malikidir.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/4.mp3", juz: 1, page: 1 },
      { number: 5, numberInSurah: 5, text: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ", translation: "(Rabbimiz!) Ancak Sana kulluk eder ve yalnız Senden yardım dileriz.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/5.mp3", juz: 1, page: 1 },
      { number: 6, numberInSurah: 6, text: "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ", translation: "Bizi doğru yola ilet.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6.mp3", juz: 1, page: 1 },
      { number: 7, numberInSurah: 7, text: "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ", translation: "Kendilerine nimet verdiklerinin yoluna; gazaba uğramışların ve sapmışların yoluna değil.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/7.mp3", juz: 1, page: 1 }
    ]
  },
  112: {
    ...STATIC_SURAHS[111],
    ayahs: [
      { number: 6222, numberInSurah: 1, text: "قُل * هُوَ اللَّهُ أَحَدٌ", translation: "De ki: O, Allah'tır, tektir.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6222.mp3", juz: 30, page: 604 },
      { number: 6223, numberInSurah: 2, text: "اللَّهُ الصَّمَدُ", translation: "Allah sameddir (her şey O'na muhtaçtır, O hiçbir şeye muhtaç değildir).", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6223.mp3", juz: 30, page: 604 },
      { number: 6224, numberInSurah: 3, text: "لَمْ يَلِدْ وَلَمْ يُولَدْ", translation: "O, doğurmamış ve doğurulmamıştır.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6224.mp3", juz: 30, page: 604 },
      { number: 6225, numberInSurah: 4, text: "وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ", translation: "Hiçbir şey O'na denk ve benzer değildir.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6225.mp3", juz: 30, page: 604 }
    ]
  },
  113: {
    ...STATIC_SURAHS[112],
    ayahs: [
      { number: 6226, numberInSurah: 1, text: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ", translation: "De ki: Sabahın Rabbine sığınırım.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6226.mp3", juz: 30, page: 604 },
      { number: 6227, numberInSurah: 2, text: "مِنْ شَرِّ مَا خَلَقَ", translation: "Yarattığı şeylerin şerrinden.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6227.mp3", juz: 30, page: 604 },
      { number: 6228, numberInSurah: 3, text: "وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ", translation: "Karanlığı çöktüğü zaman gecenin şerrinden.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6228.mp3", juz: 30, page: 604 },
      { number: 6229, numberInSurah: 4, text: "وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ", translation: "Düğümlere üfleyen büyücülerin şerrinden.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6229.mp3", juz: 30, page: 604 },
      { number: 6230, numberInSurah: 5, text: "وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ", translation: "Ve haset ettiği vakit hasetçinin şerrinden.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6230.mp3", juz: 30, page: 604 }
    ]
  },
  114: {
    ...STATIC_SURAHS[113],
    ayahs: [
      { number: 6231, numberInSurah: 1, text: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ", translation: "De ki: İnsanların Rabbine sığınırım.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6231.mp3", juz: 30, page: 605 },
      { number: 6232, numberInSurah: 2, text: "مَلِكِ النَّاسِ", translation: "İnsanların malikine (hükümdarına).", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6232.mp3", juz: 30, page: 605 },
      { number: 6233, numberInSurah: 3, text: "إِلَٰهِ النَّاسِ", translation: "İnsanların ilâhına.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6233.mp3", juz: 30, page: 605 },
      { number: 6234, numberInSurah: 4, text: "مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ", translation: "Sinsi vesvesecinin şerrinden.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6234.mp3", juz: 30, page: 605 },
      { number: 6235, numberInSurah: 5, text: "الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ", translation: "O ki insanların göğüslerine vesvese verir.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6235.mp3", juz: 30, page: 605 },
      { number: 6236, numberInSurah: 6, text: "مِنَ الْجِنَّةِ وَالنَّاسِ", translation: "Gerek cinlerden, gerekse insanlardan.", audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/6236.mp3", juz: 30, page: 605 }
    ]
  }
};
